server:
  port: 8351
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: message-manage-provider
eureka:
  client:
    service-url:
      defaultZone: http://lingfox:huli0911@localhost:8352/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
