spring:
  application:
    name: message-manage-client
  thymeleaf: 
    prefix: /WEB-INF/   #默认templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
  resources:
    static-locations: /WEB-INF # 修改默认的静态寻址资源目录
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smm?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  cloud:
    config:
      uri: http://localhost:8351
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: 'classpath*:mapper/**/*Mapper.xml'
  type-aliases-package: 'org.message.manage.client.model'
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
feign:
  hystrix:
    enabled: true
server:
  port: 8355
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://lingfox:huli0911@localhost:8352/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}} 
logging:
  level:
    org.springframework.cloud.sleuth: DEBUG #日志收集
